### ISSUE TITLE
Actually react to HA events

### ISSUE THREAD

**Issue by plajjan** [plajjan/bgworker#10]
Silly me, I implemented a thread to listen to the notification API in NCS and subscribe to HA events.. and we put those events on the main supervisor queue but the supervisor doesn't actually react to them. FIX IT!!!

**Comment by mzagozen** [comment]
Implemented in https://github.com/mzagozen/bgworker/tree/10-react-ha-stable.
I based it off of 4b26ded7347fb12753236c36bf255bf6aa878073, before the `select` branch was merged.
