### ISSUE TITLE
React to HA enabled/disabled

### ISSUE THREAD

**Issue by plajjan** [plajjan/bgworker#13]
While we react to changes in HA mode changes like becoming master, the whole HA mode can be enabled or disabled and we only read this once on startup. Should we not listen to this too?

**Comment by mzagozen** [comment]
HA is enabled in ncs.conf, by setting the enabled leaf:
```xml
<ha>
  <enabled>true</enabled>
</ha>
```

It is not possible to change this value to any effect without restarting NSO. `ncs --reload` didn't do anything. It is safe to only read this in on startup.

**Comment by plajjan** [comment]
Ok, very good. I thought a reload would honour the new value. Then our code is good. I think we should document this for anyone else wondering...
